import json
from datetime import datetime

def generate_readme(results):
    readme = f"""# Selenium Image Checker Report

Last updated: {results['timestamp']}

## Summary

| URL | Chrome Status | Firefox Status |
|-----|---------------|----------------|
"""

    for url in results['chrome']:
        chrome_status = results['chrome'][url]['status']
        firefox_status = results['firefox'][url]['status']
        readme += f"| {url} | {chrome_status} | {firefox_status} |\n"

    readme += """
## Details

For more detailed information, please check the [full report](https://adtpdn.github.io/selenium-image-checker/).

## About

This report is automatically generated by the Selenium Image Checker. It checks for missing images on specified URLs using both Chrome and Firefox browsers.
"""

    return readme

with open('results.json', 'r') as f:
    results = json.load(f)

readme_content = generate_readme(results)

with open('README.md', 'w') as f:
    f.write(readme_content)